server:
  port: 1000
  
  
okta:
  oauth2:
    issuer: https://dev-03131466.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa99yt607oaOaYYv5d7
    client-secret: fxATTkPYVUGXK5wuh9M2dIu0FVukIfOT-BB4J9zP
    scopes: openid, profile, email, offline_access
      